version: 2.1
orbs:
  bun: ksylvest/bun@1.0.1

jobs:
  build:
    docker:
      - image: cimg/node:20.11.1
    resource_class: small
    steps:
      - checkout
      - bun/install
      - restore_cache:
          keys:
            - v1-bun-deps-{{ checksum "bun.lockb" }}
            - v1-bun-deps-
      - run:
          name: Install  project dependencies
          command: bun install
      - save_cache:
          key: v1-bun-deps-{{ checksum "bun.lockb" }}
          paths:
            - ~/.bun/install/cache
            - node_modules
      - run:
          name: Build web
          command: bun run build

  quality-gate:
    docker:
      - image: mcr.microsoft.com/playwright:v1.42.1-jammy
    steps:
      - checkout
      - run:
          name: Update packages
          command: apt-get update
      - run:
          name: Install unzip package
          command: apt-get -y install unzip
      - bun/install
      - restore_cache:
          keys:
            - v1-bun-deps-{{ checksum "bun.lockb" }}
            - v1-bun-deps-
      - run:
          name: Install  project dependencies
          command: bun install
      - save_cache:
          key: v1-bun-deps-{{ checksum "bun.lockb" }}
          paths:
            - ~/.bun/install/cache
            - node_modules
      - run:
          name: Install playwright dependencies
          command: npx playwright install --with-deps chrome msedge
      - run:
          name: Running tests coverage
          command: bun run coverage
      - run:
          name: Running end-to-end tests
          command: bun run e2e:test
      - store_artifacts:
          path: playwright-report/index.html

  release:
    docker:
      - image: cimg/node:20.11.1
    resource_class: small
    steps:
      - checkout
      - bun/install
      - restore_cache:
          keys:
            - v1-bun-deps-{{ checksum "bun.lockb" }}
            - v1-bun-deps-
      - run:
          name: Install  project dependencies
          command: bun install
      - save_cache:
          key: v1-bun-deps-{{ checksum "bun.lockb" }}
          paths:
            - ~/.bun/install/cache
            - node_modules
      - run:
          name: Update version number, generate release notes and publish to GitHub
          command: bun x semantic-release

workflows:
  build-quality-release:
    jobs:
      - build
      - quality-gate
      - release:
          requires:
            - build
            - quality-gate
          filters:
            branches:
              only: master
