import Head from "next/head";
import Typography from "@mui/material/Typography";
import Stack from "@mui/material/Stack";
import { RecipeList, SearchBar, Footer } from "components";
import Container from "@mui/material/Container";

export default function Home() {
  return (
    <>
      <Head>
        <title>Nak Masak Apa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container
        sx={{
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          paddingBlock: 5,
        }}
      >
        <Stack spacing={10}>
          <div>
            <Typography
              sx={{ color: "#333333", textAlign: "center" }}
              fontWeight={700}
              variant="h3"
              mt={10}
            >
              Wasssup guys, Cari Resepi
            </Typography>
            <Typography
              sx={{ color: "#333333", textAlign: "center" }}
              fontWeight={700}
              variant="h3"
            >
              <span style={{ color: "#F4A261" }}>Khairul Aming </span>
              <span>Di Sini</span>
            </Typography>
          </div>
          <Stack spacing={10} style={{ alignItems: "center" }}>
            <SearchBar />
            <RecipeList />
          </Stack>
        </Stack>
      </Container>
      <Footer />
    </>
  );
}
