import { useState } from "react";
import Head from "next/head";
import Chip from "@mui/material/Chip";
import Container from "@mui/material/Container";
import Stack from "@mui/material/Stack";
import Typography from "@mui/material/Typography";
import { Footer, RecipeList, SearchBar } from "components";

const Home = () => {
  const [searchValue, setSearchValue] = useState("");

  const onChangeSearchValue = (value: string) => {
    setSearchValue(value);
  };

  return (
    <>
      <Head>
        <title>Nak Masak Apa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container
        sx={{
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          paddingBlock: 5,
        }}
      >
        <Stack spacing={10}>
          <Container
            sx={{
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              justifyContent: "center",
            }}
          >
            <Typography
              sx={{ color: "#333333", textAlign: "center" }}
              fontWeight={700}
              variant="h3"
              mt={10}
            >
              Wasssup guys, Cari Resepi
            </Typography>
            <Typography
              sx={{ color: "#333333", textAlign: "center" }}
              fontWeight={700}
              variant="h3"
              mb={2.5}
            >
              <span style={{ color: "#F4A261" }}>Khairul Aming </span>
              <span>Di Sini</span>
            </Typography>
            <Chip
              sx={{
                backgroundColor: "#333333",
                color: "whiteSmoke",
                paddingInline: 1,
              }}
              label="2023 Edition"
            />
          </Container>
          <Stack spacing={10} style={{ alignItems: "center" }}>
            <SearchBar onChange={onChangeSearchValue} />
            <RecipeList searchValue={searchValue} />
          </Stack>
        </Stack>
      </Container>
      <Footer />
    </>
  );
};

export default Home;
