import Head from "next/head";
import { Inter } from "next/font/google";
import Typography from "@mui/material/Typography";
import Stack from "@mui/material/Stack";
import { ProductList, SearchBar, Footer } from "components";
import styles from "styles/Home.module.css";
import Container from "@mui/material/Container";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Nak Masak Apa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container
        sx={{
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          paddingBlock: 5,
        }}
      >
        <Typography
          sx={{ color: "#27272A", textAlign: "center" }}
          fontWeight={700}
          variant="h2"
          mt={10}
        >
          Cari Pelbagai Resepi Masakan
        </Typography>
        <Typography
          sx={{ color: "#27272A", textAlign: "center" }}
          fontWeight={700}
          variant="h2"
        >
          Khairul Aming
        </Typography>

        <Typography sx={{ mt: "40px" }} mb={5} variant="subtitle1">
          Nak masak apa hari ni?
        </Typography>
        <Stack spacing={5} style={{ alignItems: "center" }}>
          <SearchBar />
          <ProductList />
        </Stack>
      </Container>
      <Footer />
    </>
  );
}
