export const recipes = [
  {
    title: "Popia Simpul & Popia Seaweed",
    url: "https://www.instagram.com/p/CrPnyKbgsMF/?hl=en",
    createdAt: "2023-04-20",
    thumbnail: "/recipes/37.jpeg",
  },
  {
    title: "Pulut Kuning",
    url: "https://www.instagram.com/p/CrNO7DQgKRf/?hl=en",
    createdAt: "2023-04-19",
    thumbnail: "/recipes/36.jpeg",
  },
  {
    title: "Resepi Rendang 1 Ekor Ayam",
    url: "https://www.instagram.com/p/CrKjDlSAHJ7/?hl=en",
    createdAt: "2023-04-18",
    thumbnail: "/recipes/35.jpeg",
  },
  {
    title: "Kek Coklat Kukus ",
    url: "https://www.instagram.com/p/CrH9y5jAcNt/?hl=en",
    createdAt: "2023-04-17",
    thumbnail: "/recipes/34.jpeg",
  },
  {
    title: "Nasi Tomato & Acar",
    url: "https://www.instagram.com/p/CrFkDzwgApr/?hl=en",
    createdAt: "2023-04-16",
    thumbnail: "/recipes/33.jpeg",
  },
  {
    title: "Daging Dendeng",
    url: "https://www.instagram.com/p/CrC60MkgBdE/?hl=en",
    createdAt: "2023-04-15",
    thumbnail: "/recipes/32.jpeg",
  },
  {
    title: "Cadbury Tart",
    url: "https://www.instagram.com/p/CrAN9fZgEUG/?hl=en",
    createdAt: "2023-04-14",
    thumbnail: "/recipes/31.jpeg",
  },
  {
    title: "Cornflakes Madu Biscoff",
    url: "https://www.instagram.com/p/Cq9wLgAg_xJ/?hl=en",
    createdAt: "2023-04-13",
    thumbnail: "/recipes/30.jpeg",
  },
  {
    title: "Lontong Kuah Lodeh ",
    url: "https://www.instagram.com/p/Cq7GRdZAMW-/?hl=en",
    createdAt: "2023-04-12",
    thumbnail: "/recipes/29.jpeg",
  },
  {
    title: "Chicken Alfredo Pasta",
    url: "https://www.instagram.com/p/Cq4lSTeA6xF/?hl=en",
    createdAt: "2023-04-11",
    thumbnail: "/recipes/28.jpeg",
  },
  {
    title: "Salted Egg Chicken",
    url: "https://www.instagram.com/p/Cq1_aAQAPnK/?hl=en",
    createdAt: "2023-04-10",
    thumbnail: "/recipes/27.jpeg",
  },
  {
    title: "Nasi Goreng Belacan ala Thai",
    url: "https://www.instagram.com/p/CqzgF0lAfEs/?hl=en",
    createdAt: "2023-04-09",
    thumbnail: "/recipes/26.jpeg",
  },
  {
    title: "Pisang Custard Butterscotch",
    url: "https://www.instagram.com/p/Cqw7vWbAapF/?hl=en",
    createdAt: "2023-04-08",
    thumbnail: "/recipes/25.jpeg",
  },
  {
    title: "Tom Kha Gai",
    url: "https://www.instagram.com/p/CquFs3KAG1h/?hl=en",
    createdAt: "2023-04-07",
    thumbnail: "/recipes/24.jpeg",
  },
  {
    title: "Roti Puri Cicah Sardin Tumis",
    url: "https://www.instagram.com/p/CqrlkvqAIDr/?hl=en",
    createdAt: "2023-04-06",
    thumbnail: "/recipes/23.jpeg",
  },
  {
    title: "Chocolate ala Royce",
    url: "https://www.instagram.com/p/CqpEQX6AZSU/?hl=en",
    createdAt: "2023-04-05",
    thumbnail: "/recipes/22.jpeg",
  },
  {
    title: "Ayam Masak Bali",
    url: "https://www.instagram.com/p/CqmgRMLAtXZ/?hl=en",
    createdAt: "2023-04-04",
    thumbnail: "/recipes/21.jpeg",
  },
  {
    title: "Ketam Masak Lemak Cili Api",
    url: "https://www.instagram.com/p/CqkAxR1A0tW/?hl=en",
    createdAt: "2023-04-03",
    thumbnail: "/recipes/20.jpeg",
  },
  {
    title: "Creamy Tomyam Pasta",
    url: "https://www.instagram.com/p/CqhYxWmguO2/?hl=en",
    createdAt: "2023-04-02",
    thumbnail: "/recipes/19.jpeg",
  },
  {
    title: "Creamy Sagu Mangga",
    url: "https://www.instagram.com/p/Cqe0P3uAa2J/?hl=en",
    createdAt: "2023-04-01",
    thumbnail: "/recipes/18.jpeg",
  },
  {
    title: "Sambal Hijau Bilis & Telur Dadar ",
    url: "https://www.instagram.com/p/CqcJuJ4AiSP/?hl=en",
    createdAt: "2023-03-31",
    thumbnail: "/recipes/17.jpeg",
  },
  {
    title: "Nasi Goreng Pattaya",
    url: "https://www.instagram.com/p/CqZ5BvnAhxj/?hl=en",
    createdAt: "2023-03-30",
    thumbnail: "/recipes/16.jpeg",
  },
  {
    title: "Ayam Phat Phet Thai & Sirap Lemon Selasih",
    url: "https://www.instagram.com/p/CqZlrJSAYJs/?hl=en",
    createdAt: "2023-03-30",
    thumbnail: "/recipes/15.jpeg",
  },
  {
    title: "Nanas Laici Sparkling",
    url: "https://www.instagram.com/p/CqXUmbFAcg-/?hl=en",
    createdAt: "2023-03-29",
    thumbnail: "/recipes/14.jpeg",
  },
  {
    title: "Colek Seafood Celup Tepung Goreng-goreng",
    url: "https://www.instagram.com/p/CqXEmyFAFfm/?hl=en",
    createdAt: "2023-03-29",
    thumbnail: "/recipes/13.jpeg",
  },
  {
    title: "Ayam Goreng Mamak",
    url: "https://www.instagram.com/p/CqUavZSAc2O/?hl=en",
    createdAt: "2023-03-28",
    thumbnail: "/recipes/12.jpeg",
  },
  {
    title: "Soya Ais Campur",
    url: "https://www.instagram.com/p/CqSKqAHAOoO/?hl=en",
    createdAt: "2023-03-27",
    thumbnail: "/recipes/11.jpeg",
  },
  {
    title: "Daging Harimau Menangis",
    url: "https://www.instagram.com/p/CqR3_yTAm-3/?hl=en",
    createdAt: "2023-03-27",
    thumbnail: "/recipes/10.jpeg",
  },
  {
    title: "Agar-agar Buah",
    url: "https://www.instagram.com/p/CqPVczQgN4z/?hl=en",
    createdAt: "2023-03-26",
    thumbnail: "/recipes/9.jpeg",
  },
  {
    title: "Cencaru Sumbat Sambal & Sayur Masak Lemak",
    url: "https://www.instagram.com/p/CqMtbYhA3Sv/?hl=en",
    createdAt: "2023-03-25",
    thumbnail: "/recipes/8.jpeg",
  },
  {
    title: "Ayam Gepuk",
    url: "https://www.instagram.com/p/CqKFlyBALVl/?hl=en",
    createdAt: "2023-03-24",
    thumbnail: "/recipes/7.jpeg",
  },
  {
    title:
      "4 Menu Air Berbuka : Teh Bunga Longan, Orange Juice Soda, Bandung Laici & Coconut Shake Gula Melaka",
    url: "https://www.instagram.com/p/CqHjGoKA0QV/?hl=en",
    createdAt: "2023-03-23",
    thumbnail: "/recipes/6.jpeg",
  },
  {
    title: "Telur Mata Goreng Cili Padi",
    url: "https://www.instagram.com/p/CqFzLXVA1ja/?hl=en",
    createdAt: "2023-03-22",
    thumbnail: "/recipes/5.jpeg",
  },
  {
    title: "Kek Pisang Chocolate Chip",
    url: "https://www.instagram.com/p/Cpjg7dxgGrt/?hl=en",
    createdAt: "2023-03-09",
    thumbnail: "/recipes/4.jpeg",
  },
  {
    title: "Donut Susu Gebu",
    url: "https://www.instagram.com/p/CpReM1ZAkhd/?hl=en",
    createdAt: "2023-03-02",
    thumbnail: "/recipes/3.jpeg",
  },
  {
    title: "Maggi Goreng Basah",
    url: "https://www.instagram.com/p/Co3wHHUAmbS/?hl=en",
    createdAt: "2023-02-20",
    thumbnail: "/recipes/2.jpeg",
  },
  {
    title: "Kerabu Maggi Thai",
    url: "https://www.instagram.com/p/Cm8zkcShY5K/?hl=en",
    createdAt: "2023-01-03",
    thumbnail: "/recipes/1.jpeg",
  },
];
